In [2]:
from google.colab import files
uploaded = files.upload()

In [ ]:
import pandas as pd
import numpy as np


In [1]:
df1=pd.read_csv("Book1.csv")

NameError: ignored

In [ ]:
df1.head()

TVD     CALI       GR     LLD     LLS    NPHI    RHOB  K(md)
0  827.6544  12.2811  19.1587  0.4839  0.1552  0.4637  1.8088    4.0
1  827.7595  12.2063  18.4251  0.4901  0.1551  0.4498  1.8524    5.0
2  827.8646  12.2179  16.5793  0.5016  0.1548  0.4574  1.9054    6.0
3  827.9698  12.1898  15.6918  0.4987  0.1553  0.4489  1.9441    6.0
4  828.0749  12.2659  16.5485  0.5105  0.1550  0.4206  1.9508    5.4

In [ ]:
X = df1.iloc[:,:-1].values

In [ ]:
X

In [ ]:
y = df1.iloc[:,-1].values

In [ ]:
y

array([4. , 5. , 6. , 6. , 5.4, 7.5, 8. , 5.5, 4. , 6. , 5.5, 4.2, 3.5,
       3. , 6. , 4. , 4.5, 5. , 5.9, 6. , 3. , 8. , 5.4])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred = regressor.predict(X_test)

In [ ]:
y_pred

array([5.64198208, 6.0568998 , 5.045942  , 6.67778834, 4.94796478])

In [ ]:
y_pred == y_test

array([False, False, False, False, False])

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score


In [ ]:
print('Coefficients: \n', regressor.coef_)
# The mean squared error
print('Mean squared error: %.2f'
      % mean_squared_error(y_test, y_pred))
# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f'
      % r2_score(y_test, y_pred))

Coefficients: 
 [ 2.49343692e-01  8.27627201e+00  2.68660977e-01  5.18515805e+00
 -3.29275037e+02 -1.55493597e+01  1.08636282e+01]
Mean squared error: 2.19
Coefficient of determination: -2.43


In [ ]:
df1.size

184

In [ ]:
df1.shape

(23, 8)

In [ ]:
X_test.size

35

In [ ]:
y_test.size

5

In [ ]:
print(y_train.size)
print(X_train.size)

18
126


In [ ]:
plt.plot(X_test, y_test, linewidth=2.0)

In [ ]:
import seaborn as sns

In [ ]:
sns.pairplot(df1)

In [ ]:
sns.pairplot(df1, hue = 'K(md)', diag_kind = 'scatter',
             plot_kws = {'alpha': 0.6, 's': 80, 'edgecolor': 'k'},
             size = 4)

In [ ]:
 r2_score(y_test,y_pred)

-2.42706107390953

In [ ]:
y_test

array([4., 6., 4., 4., 5.])

In [ ]:
y_pred

array([5.64198208, 6.0568998 , 5.045942  , 6.67778834, 4.94796478])