In [3]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
from mpl_toolkits.axes_grid1.axes_divider import make_axes_locatable
from matplotlib.colors import ListedColormap
%matplotlib inline 

In [1]:
from google.colab import files
uploaded = files.upload()

Saving log_proj.xlsx to log_proj.xlsx


In [4]:
df1 = pd.read_excel("log_proj.xlsx")

In [5]:
df1.head()

#Depth     BVW    PHIF SAND_FLAG  ...    NPHI    RHOB      RT  KLOGH
0      #M     V/V     V/V  unitless  ...     v/v   g/cm3   ohm.m     mD
1  3429.4  0.0791  0.1279         0  ...  0.3147  2.4477  3.3667  0.001
2  3429.5  0.0804  0.1248         0  ...  0.3038  2.4529  3.2573  0.001
3  3429.6  0.0938  0.1176         0  ...  0.2948  2.4649  2.3957  0.001
4  3429.7  0.1036  0.1036         0  ...  0.2886  2.4882   1.318  0.001

[5 rows x 17 columns]

In [13]:
df  = df1.drop(df1.index[0])
df

#Depth     BVW    PHIF SAND_FLAG  ...    NPHI    RHOB      RT  KLOGH
1     3429.4  0.0791  0.1279         0  ...  0.3147  2.4477  3.3667  0.001
2     3429.5  0.0804  0.1248         0  ...  0.3038  2.4529  3.2573  0.001
3     3429.6  0.0938  0.1176         0  ...  0.2948  2.4649  2.3957  0.001
4     3429.7  0.1036  0.1036         0  ...  0.2886  2.4882   1.318  0.001
5     3429.8  0.0813  0.0813         0  ...  0.2839  2.5251  0.5944  0.001
...      ...     ...     ...       ...  ...     ...     ...     ...    ...
2277    3657  0.0238  0.0238         0  ...   0.188  2.6083  2.5325  0.001
2278  3657.1  0.0231  0.0231         0  ...  0.1917  2.6096  2.4761  0.001
2279  3657.2  0.0225  0.0225         0  ...  0.2204  2.6107  2.4062  0.001
2280  3657.3  0.0223  0.0223         0  ...  0.2108  2.6109  2.3991  0.001
2281  3657.4   0.022   0.022         0  ... -999.25  2.6115  2.3955  0.001

[2281 rows x 17 columns]

In [19]:
df = df.drop(['SW'], axis = 1) 

In [23]:
df = df.reindex(columns=['DEPTH','NPHI', 'RHOB', 'GR', 'RT', 'DT', 'CALI', 'KLOGH'])

In [25]:
df = df.loc[(df['DEPTH'] >= 3200) & (df1['DEPTH'] <= 4740)]

In [24]:
df

DEPTH    NPHI    RHOB       GR      RT       DT    CALI  KLOGH
1       NaN  0.3147  2.4477  75.1558  3.3667  90.1318   8.625  0.001
2       NaN  0.3038  2.4529  71.3661  3.2573  90.2611   8.625  0.001
3       NaN  0.2948  2.4649  65.6189  2.3957  90.3901   8.625  0.001
4       NaN  0.2886  2.4882  58.8824   1.318  90.4287   8.625  0.001
5       NaN  0.2839  2.5251  53.5104  0.5944  90.4576   8.625  0.001
...     ...     ...     ...      ...     ...      ...     ...    ...
2277    NaN   0.188  2.6083   101.82  2.5325  -999.25   8.672  0.001
2278    NaN  0.1917  2.6096  100.497  2.4761  -999.25  8.6927  0.001
2279    NaN  0.2204  2.6107  97.6597  2.4062  -999.25   8.703  0.001
2280    NaN  0.2108  2.6109  95.4315  2.3991  -999.25  8.6719  0.001
2281    NaN -999.25  2.6115  96.9069  2.3955  -999.25  8.6719  0.001

[2281 rows x 8 columns]

In [ ]:
X = df.iloc[:,:-1].values

In [ ]:
X

array([[3429.4, 0.0791, 0.1279, ..., 0.3147, 2.4477, 3.3667],
       [3429.5, 0.0804, 0.1248, ..., 0.3038, 2.4529, 3.2573],
       [3429.6, 0.0938, 0.1176, ..., 0.2948, 2.4649, 2.3957],
       ...,
       [3657.2, 0.0225, 0.0225, ..., 0.2204, 2.6107, 2.4062],
       [3657.3, 0.0223, 0.0223, ..., 0.2108, 2.6109, 2.3991],
       [3657.4, 0.022, 0.022, ..., -999.25, 2.6115, 2.3955]], dtype=object)

In [ ]:
y = df.iloc[:,-1].values

In [ ]:

print(y)

[0.001 0.001 0.001 ... 0.001 0.001 0.001]


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred = regressor.predict(X_test)

In [ ]:
y_pred

array([ 2.58739358e+02,  1.05961070e+02,  2.29356296e+01, -2.01320823e+01,
       -1.91538803e+02,  1.02738891e+01, -1.56206940e+00, -1.99364989e+02,
       -1.23291254e+02,  1.77234396e+02, -2.77824076e+01,  1.38718674e+02,
        2.22864939e+02,  5.80082583e+01, -1.80122551e+02,  6.98304592e+00,
       -1.07082445e+01,  1.65496027e+02,  1.17911358e+00,  2.47842118e+02,
       -3.99865526e+01, -1.88601573e+02,  4.73323111e+01, -1.20981867e+02,
        1.32761905e+02, -1.99160583e+02, -1.43278293e+02, -1.74174482e+02,
       -9.16509697e+01,  2.35535130e+02,  5.69264935e+00, -1.62066008e+02,
       -4.85797497e+01, -4.08500601e+01, -7.09352876e+01,  1.66706545e+02,
        2.53910188e+02,  3.61460420e+02,  1.14178847e+02,  5.30790310e+02,
       -1.53006230e+02, -2.63021100e+01,  2.20679606e+02,  1.97694065e+02,
        1.33488756e+02, -9.47296209e+00, -4.10295048e+01,  2.08579073e+01,
        5.52360714e+01, -4.78698213e+01, -7.89485195e+01,  1.83351509e+02,
        1.46652621e+02,  

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
print('Coefficients: \n', regressor.coef_)
# The mean squared error
print('Mean squared error: %.2f'
      % mean_squared_error(y_test, y_pred))
# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f'
      % r2_score(y_test, y_pred))

Coefficients: 
 [-8.20054493e-01  6.77696411e+03 -3.10879494e+03 -2.90723499e+02
  1.16257010e+02 -3.36854239e+02 -2.49215267e+02  6.35047570e-12
 -1.16316261e+03 -5.97091733e+02  1.93826312e-01 -3.05526660e-01
  3.26536466e-01 -3.65975743e-02  9.09842884e+01  1.77031063e+01]
Mean squared error: 79952.79
Coefficient of determination: 0.08
