In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
dataset = pd.read_excel("C:\\Users\\RGIPT\\Desktop\\well log.xlsx")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

FileNotFoundError: ignored

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
dataset.head()

#Depth     BVW  COAL_FLAG    PHIF  SAND_FLAG   SW   VCARB     VSH   KLOGH
0  3319.7  0.0200          0  0.0200          0  1.0  0.0120  0.7446  0.0010
1  3319.8  0.0200          0  0.0200          0  1.0  0.0000  0.7582  0.0010
2  3319.9  0.0200          0  0.0200          0  1.0  0.0339  0.5477  0.0017
3  3320.0  0.0238          0  0.0238          0  1.0  0.1487  0.4117  0.0306
4  3320.1  0.0413          0  0.0413          0  1.0  0.1526  0.3592  0.1252

In [ ]:
X_train

array([[3.3917e+03, 9.1600e-02, 0.0000e+00, ..., 1.0000e+00, 3.8900e-02,
        3.1730e-01],
       [3.3719e+03, 9.6100e-02, 0.0000e+00, ..., 1.0000e+00, 1.1930e-01,
        2.2860e-01],
       [3.3480e+03, 8.1700e-02, 0.0000e+00, ..., 1.0000e+00, 1.8230e-01,
        2.2020e-01],
       ...,
       [3.4850e+03, 1.0590e-01, 0.0000e+00, ..., 1.0000e+00, 3.9100e-02,
        2.7180e-01],
       [3.5804e+03, 9.5700e-02, 0.0000e+00, ..., 1.0000e+00, 1.0100e-02,
        3.3580e-01],
       [3.5929e+03, 2.0000e-02, 0.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        7.5460e-01]])

In [ ]:
 y_train

array([6.2000e-02, 1.3670e-01, 4.6976e+00, ..., 1.5040e-01, 6.4300e-02,
       1.0000e-03])

In [ ]:
 X_test

array([[3.4354e+03, 6.3300e-02, 0.0000e+00, ..., 1.0000e+00, 5.0400e-02,
        3.9360e-01],
       [3.3596e+03, 1.7990e-01, 0.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        2.0110e-01],
       [3.5339e+03, 2.0000e-02, 0.0000e+00, ..., 1.0000e+00, 5.8100e-02,
        5.1650e-01],
       ...,
       [3.4240e+03, 9.3900e-02, 0.0000e+00, ..., 1.0000e+00, 9.2700e-02,
        2.5830e-01],
       [3.5316e+03, 2.1800e-02, 0.0000e+00, ..., 1.0000e+00, 0.0000e+00,
        6.9290e-01],
       [3.3833e+03, 8.7400e-02, 0.0000e+00, ..., 1.0000e+00, 9.8500e-02,
        2.7280e-01]])

In [ ]:
 y_test

array([0.7394, 0.0292, 0.001, 26.4273, 0.001, 0.0471, 4.0667, 0.001,
       0.0304, 0.1829, 0.001, 0.1488, 191.4118, 0.001, 7.7219, 0.1384,
       0.001, 1.1794, 0.001, 0.0273, 0.9972, 0.0088, 0.1121, 0.0015,
       0.0048, 0.0825, 0.114, 0.2554, 0.0615, 0.031, 0.1504, 0.001, 0.208,
       0.4128, 0.001, 0.0571, 0.001, 0.0279, 0.043, 0.001, 0.0485, 0.5425,
       0.0445, 0.018, 0.001, 0.001, 0.0053, 0.001, 0.1544, 0.1491, 0.024,
       8.1756, 0.001, 6.9661, 0.2082, 0.0331, 0.0135, 0.0252, 0.1008,
       0.7431, 0.001, 0.4654, 0.001, 0.0242, 0.0029, 0.001, 0.0587,
       50.5954, 0.001, 0.0196, 0.0127, 2.6135, 0.001, 0.043, 0.0361,
       0.7646, 0.001, 3.5054, 0.001, 0.0282, 0.001, 0.001, 0.2883, 0.0165,
       0.1859, 0.001, 1.1075, 0.0444, 0.0275, 0.001, 0.0015, 0.0119,
       0.0259, 0.4921, 0.0295, 0.1408, 0.0747, 29.4909, 0.0729, 0.001,
       0.0257, 0.001, 0.0949, 91.896, 0.027, 4.0123, 0.1346, 0.0604,
       0.001, 0.001, 0.1112, 1.003, 0.1591, 0.1848, 0.2863, 7.9985, 0.015,
 

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(sc.fit(dataset))

StandardScaler()


In [ ]:
 print(sc.mean_)

[3.46325000e+03 7.99684540e-02 0.00000000e+00 8.15557103e-02
 3.11977716e-01 9.88601811e-01 6.07767409e-02 4.12269429e-01
 4.97043520e+00]


In [ ]:
print(dataset)

      #Depth     BVW  COAL_FLAG    PHIF  SAND_FLAG   SW   VCARB     VSH  \
0     3319.7  0.0200          0  0.0200          0  1.0  0.0120  0.7446   
1     3319.8  0.0200          0  0.0200          0  1.0  0.0000  0.7582   
2     3319.9  0.0200          0  0.0200          0  1.0  0.0339  0.5477   
3     3320.0  0.0238          0  0.0238          0  1.0  0.1487  0.4117   
4     3320.1  0.0413          0  0.0413          0  1.0  0.1526  0.3592   
...      ...     ...        ...     ...        ...  ...     ...     ...   
2867  3606.4  0.0308          0  0.0308          0  1.0  0.0000  0.8386   
2868  3606.5  0.0301          0  0.0301          0  1.0  0.0000  0.8195   
2869  3606.6  0.0312          0  0.0312          0  1.0  0.0000  0.8195   
2870  3606.7  0.0341          0  0.0341          0  1.0  0.0000  0.8202   
2871  3606.8  0.0370          0  0.0370          0  1.0  0.0000  0.8035   

       KLOGH  
0     0.0010  
1     0.0010  
2     0.0017  
3     0.0306  
4     0.1252  
...      

In [ ]:
print(X_train)

[[-0.86674906  0.26010765  0.         ...  0.21607044 -0.24961751
  -0.43286974]
 [-1.10693344  0.36219636  0.         ...  0.21607044  0.66939318
  -0.83720192]
 [-1.39685297  0.0355125   0.         ...  0.21607044  1.38951351
  -0.87549268]
 ...
 [ 0.26502887  0.58452287  0.         ...  0.21607044 -0.24733142
  -0.64027802]
 [ 1.4222809   0.3531218   0.         ...  0.21607044 -0.57881538
  -0.3485389 ]
 [ 1.57391245 -1.36423706  0.         ...  0.21607044 -0.69426324
   1.56052896]]


In [ ]:
print(X_test)

[[-0.33664514 -0.38191686  0.         ...  0.21607044 -0.11816698
  -0.08506201]
 [-1.25613889  2.26331488  0.         ...  0.21607044 -0.69426324
  -0.96255858]
 [ 0.85821151 -1.36423706  0.         ...  0.21607044 -0.03015227
   0.47516827]
 ...
 [-0.47493312  0.31228632  0.         ...  0.21607044  0.36534238
  -0.70181674]
 [ 0.83031131 -1.32340158  0.         ...  0.21607044 -0.69426324
   1.27927422]
 [-0.96864546  0.16482486  0.         ...  0.21607044  0.43163917
  -0.63571959]]


In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

ValueError: Unknown label type: 'continuous'

In [ ]:
X_train

array([[-0.86674906,  0.26010765,  0.        , ...,  0.21607044,
        -0.24961751, -0.43286974],
       [-1.10693344,  0.36219636,  0.        , ...,  0.21607044,
         0.66939318, -0.83720192],
       [-1.39685297,  0.0355125 ,  0.        , ...,  0.21607044,
         1.38951351, -0.87549268],
       ...,
       [ 0.26502887,  0.58452287,  0.        , ...,  0.21607044,
        -0.24733142, -0.64027802],
       [ 1.4222809 ,  0.3531218 ,  0.        , ...,  0.21607044,
        -0.57881538, -0.3485389 ],
       [ 1.57391245, -1.36423706,  0.        , ...,  0.21607044,
        -0.69426324,  1.56052896]])

In [ ]:
 y_train

array([6.2000e-02, 1.3670e-01, 4.6976e+00, ..., 1.5040e-01, 6.4300e-02,
       1.0000e-03])

In [ ]:
from sklearn.linear_model import LinearRegression
clf = LinearRegression().fit(X_train, y_train)

In [ ]:
prediction=clf.predict(X_train)
from sklearn.metrics import r2_score
r2_score(y_train, prediction)

0.04288178899659478

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

ValueError: Unknown label type: 'continuous'

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
pf = PolynomialFeatures(degree=2, interaction_only=False, include_bias=False)  
                       
    
res = pf.fit_transform(atk_def)
res

Output
------
array([[    49.,     49.,   2401.,   2401.,   2401.],
       [    62.,     63.,   3844.,   3906.,   3969.],
       [    82.,     83.,   6724.,   6806.,   6889.],
       ..., 
       [   110.,     60.,  12100.,   6600.,   3600.],
       [   160.,     60.,  25600.,   9600.,   3600.],
       [   110.,    120.,  12100.,  13200.,  14400.]])

SyntaxError: invalid syntax (<ipython-input-47-c9464eeb4327>, line 9)

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
pf = PolynomialFeatures(degree=2, interaction_only=False,include_bias=False)  
                        
res = pf.fit_transform(atk_def)
res

NameError: name 'atk_def' is not defined

In [ ]:
from sklearn.svm import SVR

In [ ]:
model=SVR(kernel='rbf', gamma='auto')
model.fit(X_train, y_train)

SVR(gamma='auto')

In [ ]:
pred=model.predict(X_train)

In [ ]:
pred

array([ 0.0241311 ,  0.72854148,  1.35162111, ..., -0.09948034,
        0.15481689,  0.07726948])

In [ ]:
y_train

array([6.2000e-02, 1.3670e-01, 4.6976e+00, ..., 1.5040e-01, 6.4300e-02,
       1.0000e-03])

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_train, pred)

0.02452383957532811