In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv("C:\\Users\\RGIPT\\Desktop\\well_log.csv)

SyntaxError: EOL while scanning string literal (<ipython-input-3-a045cd92da4d>, line 1)

In [5]:
data = pd.read_csv("C:\\Users\\RGIPT\\Desktop\\Social_Network_Ads.csv")

In [6]:
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [8]:
X = data.iloc[:, :-1].values

In [9]:
datalog = pd.read_excel("C:\\Users\\RGIPT\\Desktop\\Book1.xlsx")

In [10]:
datalog.head()

#Depth     BVW COAL_FLAG   KLOGH    PHIF SAND_FLAG      SW   VCARB     VSH
0      #M     V/V  unitless      MD     V/V  unitless     V/V     V/V     V/V
1    3271 -999.25         0 -999.25 -999.25   -999.25 -999.25 -999.25  0.8769
2  3271.1 -999.25         0 -999.25 -999.25   -999.25 -999.25 -999.25  0.9546
3  3271.2 -999.25         0 -999.25 -999.25   -999.25 -999.25 -999.25  1.0114
4  3271.3 -999.25         0 -999.25 -999.25   -999.25 -999.25 -999.25  1.0456

In [11]:
datalog.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3611 entries, 0 to 3610
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   #Depth     3611 non-null   object
 1   BVW        3611 non-null   object
 2   COAL_FLAG  3611 non-null   object
 3   KLOGH      3611 non-null   object
 4   PHIF       3611 non-null   object
 5   SAND_FLAG  3611 non-null   object
 6   SW         3611 non-null   object
 7   VCARB      3611 non-null   object
 8   VSH        3611 non-null   object
dtypes: object(9)
memory usage: 254.0+ KB


In [13]:
dataf= pd.read_excel("C:\\Users\\RGIPT\\Desktop\\Book1.xlsx")

In [14]:
dataf.head()

#Depth     BVW COAL_FLAG    PHIF SAND_FLAG   SW   VCARB     VSH   KLOGH
0      #M     V/V  unitless     V/V  unitless  V/V     V/V     V/V      MD
1  3319.7    0.02         0    0.02         0    1   0.012  0.7446   0.001
2  3319.8    0.02         0    0.02         0    1       0  0.7582   0.001
3  3319.9    0.02         0    0.02         0    1  0.0339  0.5477  0.0017
4    3320  0.0238         0  0.0238         0    1  0.1487  0.4117  0.0306

In [16]:
X = dataf.iloc[:, :-1].values

In [17]:
X

array([['#M', 'V/V', 'unitless', ..., 'V/V', 'V/V', 'V/V'],
       [3319.7, 0.02, 0, ..., 1, 0.012, 0.7446],
       [3319.8, 0.02, 0, ..., 1, 0, 0.7582],
       ...,
       [3606.6, 0.0312, 0, ..., 1, 0, 0.8195],
       [3606.7, 0.0341, 0, ..., 1, 0, 0.8202],
       [3606.8, 0.037, 0, ..., 1, 0, 0.8035]], dtype=object)

In [18]:
X.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [19]:
Y = dataf.iloc[:, -1].values

In [20]:
Y

array(['MD', 0.001, 0.001, ..., 0.001, 0.001, 0.001], dtype=object)

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [35]:
print(X_train)

[[3457.2 0.0982 0 ... 1 0.1979 0.1612]
 [3383.2 0.099 0 ... 1 0.0833 0.2513]
 [3391.9 0.0829 0 ... 1 0.0895 0.2945]
 ...
 [3484.9 0.1121 0 ... 1 0.0397 0.2515]
 [3580.3 0.0733 0 ... 1 0.0531 0.3599]
 [3592.8 0.02 0 ... 1 0 0.6926]]


In [36]:
print(Y_train)

[0.2371 0.1312 0.0511 ... 0.2216 0.0222 0.001]


In [37]:
X_test

array([[3375.9, 0.1314, 0, ..., 1, 0.0406, 0.189],
       [3404.8, 0.0643, 0, ..., 1, 0.1853, 0.2676],
       [3546.7, 0.0334, 0, ..., 1, 0, 0.5708],
       ...,
       [3597, 0.0431, 0, ..., 1, 0, 0.7568],
       [3482.8, 0.0745, 0, ..., 1, 0.2294, 0.2059],
       [3512.3, 0.1217, 0, ..., 1, 0, 0.2942]], dtype=object)

In [27]:
Y_test

array([0.7394, 0.0292, 0.001, 26.4273, 0.001, 0.0471, 4.0667, 0.001,
       0.0304, 0.1829, 0.001, 0.1488, 191.4118, 0.001, 7.7219, 0.1384,
       0.001, 1.1794, 0.001, 0.0273, 0.9972, 0.0088, 0.1121, 0.0015,
       0.0048, 0.0825, 0.114, 0.2554, 0.0615, 0.031, 0.1504, 0.001, 0.208,
       0.4128, 0.001, 0.0571, 0.001, 0.0279, 0.043, 0.001, 0.0485, 0.5425,
       0.0445, 0.018, 0.001, 0.001, 0.0053, 0.001, 0.1544, 0.1491, 0.024,
       8.1756, 0.001, 6.9661, 0.2082, 0.0331, 0.0135, 0.0252, 0.1008,
       0.7431, 0.001, 0.4654, 0.001, 0.0242, 0.0029, 0.001, 0.0587,
       50.5954, 0.001, 0.0196, 0.0127, 2.6135, 0.001, 0.043, 0.0361,
       0.7646, 0.001, 3.5054, 0.001, 0.0282, 0.001, 0.001, 0.2883, 0.0165,
       0.1859, 0.001, 1.1075, 0.0444, 0.0275, 0.001, 0.0015, 0.0119,
       0.0259, 0.4921, 0.0295, 0.1408, 0.0747, 29.4909, 0.0729, 0.001,
       0.0257, 0.001, 0.0949, 91.896, 0.027, 4.0123, 0.1346, 0.0604,
       0.001, 0.001, 0.1112, 1.003, 0.1591, 0.1848, 0.2863, 7.9985, 0.015,
 

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [32]:
dataf.drop(dataf.index[[0]])

#Depth     BVW COAL_FLAG    PHIF SAND_FLAG SW   VCARB     VSH   KLOGH
1     3319.7    0.02         0    0.02         0  1   0.012  0.7446   0.001
2     3319.8    0.02         0    0.02         0  1       0  0.7582   0.001
3     3319.9    0.02         0    0.02         0  1  0.0339  0.5477  0.0017
4       3320  0.0238         0  0.0238         0  1  0.1487  0.4117  0.0306
5     3320.1  0.0413         0  0.0413         0  1  0.1526  0.3592  0.1252
...      ...     ...       ...     ...       ... ..     ...     ...     ...
2868  3606.4  0.0308         0  0.0308         0  1       0  0.8386   0.001
2869  3606.5  0.0301         0  0.0301         0  1       0  0.8195   0.001
2870  3606.6  0.0312         0  0.0312         0  1       0  0.8195   0.001
2871  3606.7  0.0341         0  0.0341         0  1       0  0.8202   0.001
2872  3606.8   0.037         0   0.037         0  1       0  0.8035   0.001

[2872 rows x 9 columns]

In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

ValueError: could not convert string to float: '#M'